#client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   #服务注册中心的地址
    #healthcheck:
     # enabled: true   #开启健康检查
  #instance:   #一个客户端从down掉到从服务中心剔除服务，在没触发自我保护模式的前提，默认配置下，时间最多为30*3+60+90=240秒
              #30心跳间隔，90续约保持的有效时间   60调用清除服务的间隔
      #在注册完服务之后，服务提供者会维护一个心跳来告诉Eureka Server"我还活着"防止Eureka Server的“剔除任务”将该服务实力从服务
      #列表中剔除出去，我们称之为服务续约
    #lease-renewal-interval-in-seconds: 10   #默认30 用于定义服务续约任务的调用间隔时间
    #lease-expiration-duration-in-seconds: 20 #默认90 用于定义服务持续的时间
server:
  port: 8760
spring:
  application:
    name: service-hi    #服务名